version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - weather_planner/.env

  web:
    build: .
    command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    env_file:
      - weather_planner/.env

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
